### ISSUE TITLE
Won't compile on Debian Buster

### ISSUE THREAD

**Issue by four43** [dgiardini/rtl-ais#32]
I'm getting tons of errors interfacing with the rtl_sdr  library. 

```
# make
cc -c main.c -o main.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c rtl_ais.c -o rtl_ais.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c convenience.c -o convenience.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
convenience.c: In function 'atofs':
convenience.c:51:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
    suff *= 1e3;
    ~~~~~^~~~~~
convenience.c:52:3: note: here
   case 'm':
   ^~~~
convenience.c:54:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
    suff *= 1e3;
    ~~~~~^~~~~~
convenience.c:55:3: note: here
   case 'k':
   ^~~~
convenience.c: In function 'atoft':
convenience.c:78:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
    suff *= 60;
    ~~~~~^~~~~
convenience.c:79:3: note: here
   case 'm':
   ^~~~
convenience.c:81:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
    suff *= 60;
    ~~~~~^~~~~
convenience.c:82:3: note: here
   case 's':
   ^~~~
cc -c aisdecoder/aisdecoder.c -o aisdecoder/aisdecoder.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c aisdecoder/sounddecoder.c -o aisdecoder/sounddecoder.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c aisdecoder/lib/receiver.c -o aisdecoder/lib/receiver.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c aisdecoder/lib/protodec.c -o aisdecoder/lib/protodec.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c aisdecoder/lib/hmalloc.c -o aisdecoder/lib/hmalloc.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c aisdecoder/lib/filter.c -o aisdecoder/lib/filter.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc -c tcp_listener/tcp_listener.c -o tcp_listener/tcp_listener.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/
cc main.o rtl_ais.o convenience.o ./aisdecoder/aisdecoder.o ./aisdecoder/sounddecoder.o ./aisdecoder/lib/receiver.o ./aisdecoder/lib/protodec.o ./aisdecoder/lib/hmalloc.o ./aisdecoder/lib/filter.o ./tcp_listener/tcp_listener.o -o rtl_ais -lpthread -lm -L -lrtlsdr
/usr/bin/ld: rtl_ais.o: in function `rtlsdr_thread_fn':
/opt/rtl-ais/rtl_ais.c:368: undefined reference to `rtlsdr_read_async'
/usr/bin/ld: rtl_ais.o: in function `rtl_ais_start':
/opt/rtl-ais/rtl_ais.c:570: undefined reference to `rtlsdr_open'
/usr/bin/ld: /opt/rtl-ais/rtl_ais.c:610: undefined reference to `rtlsdr_set_agc_mode'
/usr/bin/ld: /opt/rtl-ais/rtl_ais.c:595: undefined reference to `rtlsdr_cancel_async'
/usr/bin/ld: /opt/rtl-ais/rtl_ais.c:596: undefined reference to `rtlsdr_close'
/usr/bin/ld: rtl_ais.o: in function `rtl_ais_cleanup':
/opt/rtl-ais/rtl_ais.c:657: undefined reference to `rtlsdr_cancel_async'
/usr/bin/ld: /opt/rtl-ais/rtl_ais.c:668: undefined reference to `rtlsdr_cancel_async'
/usr/bin/ld: /opt/rtl-ais/rtl_ais.c:673: undefined reference to `rtlsdr_close'
/usr/bin/ld: convenience.o: in function `nearest_gain':
/opt/rtl-ais/convenience.c:116: undefined reference to `rtlsdr_set_tuner_gain_mode'
/usr/bin/ld: /opt/rtl-ais/convenience.c:121: undefined reference to `rtlsdr_get_tuner_gains'
/usr/bin/ld: /opt/rtl-ais/convenience.c:126: undefined reference to `rtlsdr_get_tuner_gains'
/usr/bin/ld: convenience.o: in function `verbose_set_frequency':
/opt/rtl-ais/convenience.c:142: undefined reference to `rtlsdr_set_center_freq'
/usr/bin/ld: convenience.o: in function `verbose_set_sample_rate':
/opt/rtl-ais/convenience.c:154: undefined reference to `rtlsdr_set_sample_rate'
/usr/bin/ld: convenience.o: in function `verbose_direct_sampling':
/opt/rtl-ais/convenience.c:166: undefined reference to `rtlsdr_set_direct_sampling'
/usr/bin/ld: convenience.o: in function `verbose_offset_tuning':
/opt/rtl-ais/convenience.c:183: undefined reference to `rtlsdr_set_offset_tuning'
/usr/bin/ld: convenience.o: in function `verbose_auto_gain':
/opt/rtl-ais/convenience.c:195: undefined reference to `rtlsdr_set_tuner_gain_mode'
/usr/bin/ld: convenience.o: in function `verbose_gain_set':
/opt/rtl-ais/convenience.c:207: undefined reference to `rtlsdr_set_tuner_gain_mode'
/usr/bin/ld: /opt/rtl-ais/convenience.c:212: undefined reference to `rtlsdr_set_tuner_gain'
/usr/bin/ld: convenience.o: in function `verbose_ppm_set':
/opt/rtl-ais/convenience.c:226: undefined reference to `rtlsdr_set_freq_correction'
/usr/bin/ld: convenience.o: in function `verbose_ppm_eeprom':
/opt/rtl-ais/convenience.c:241: undefined reference to `rtlsdr_get_usb_strings'
/usr/bin/ld: convenience.o: in function `verbose_reset_buffer':
/opt/rtl-ais/convenience.c:266: undefined reference to `rtlsdr_reset_buffer'
/usr/bin/ld: convenience.o: in function `verbose_device_search':
/opt/rtl-ais/convenience.c:277: undefined reference to `rtlsdr_get_device_count'
/usr/bin/ld: /opt/rtl-ais/convenience.c:284: undefined reference to `rtlsdr_get_device_usb_strings'
/usr/bin/ld: /opt/rtl-ais/convenience.c:297: undefined reference to `rtlsdr_get_device_usb_strings'
/usr/bin/ld: /opt/rtl-ais/convenience.c:301: undefined reference to `rtlsdr_get_device_name'
/usr/bin/ld: /opt/rtl-ais/convenience.c:291: undefined reference to `rtlsdr_get_device_name'
/usr/bin/ld: /opt/rtl-ais/convenience.c:307: undefined reference to `rtlsdr_get_device_usb_strings'
/usr/bin/ld: /opt/rtl-ais/convenience.c:324: undefined reference to `rtlsdr_get_device_name'
/usr/bin/ld: /opt/rtl-ais/convenience.c:317: undefined reference to `rtlsdr_get_device_usb_strings'
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: rtl_ais] Error 1
```

Apt installed:
```
librtlsdr-dev/now 0.6-1 amd64 [installed,local]
  Software defined radio receiver for Realtek RTL2832U (development)
```

Build in debian:buster-slim docker container:
`Linux [image hash] 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 GNU/Linux`

**Comment by four43** [comment]
Oooh it works good in debian stretch. They broke that on you.
```
librtlsdr-dev/now 0.5.3-11+b2 amd64 [installed,local]
  Software defined radio receiver for Realtek RTL2832U (development)
```

There it is. 0.5.3 vs 0.6-1. Those semvers aren't exuding confidence in stability lol

**Comment by whallmann** [comment]
Here also can not compile it. Im not a crack to solve this.  Any hints for me?

makelog:
pi@AIS:~/rtl-ais $ make
cc main.o rtl_ais.o convenience.o ./aisdecoder/aisdecoder.o ./aisdecoder/sounddecod                                         er.o ./aisdecoder/lib/receiver.o ./aisdecoder/lib/protodec.o ./aisdecoder/lib/hmall                                         oc.o ./aisdecoder/lib/filter.o ./tcp_listener/tcp_listener.o -o rtl_ais -lpthread -                                         lm  -L /usr/lib/arm-linux-gnueabihf/  -L -lrtlsdr
/usr/bin/ld: rtl_ais.o: in function `rtlsdr_thread_fn':
/home/pi/rtl-ais/rtl_ais.c:368: undefined reference to `rtlsdr_read_async'
/usr/bin/ld: rtl_ais.o: in function `rtl_ais_start':
/home/pi/rtl-ais/rtl_ais.c:570: undefined reference to `rtlsdr_open'
/usr/bin/ld: /home/pi/rtl-ais/rtl_ais.c:610: undefined reference to `rtlsdr_set_agc                                         _mode'
/usr/bin/ld: /home/pi/rtl-ais/rtl_ais.c:595: undefined reference to `rtlsdr_cancel_                                         async'
/usr/bin/ld: /home/pi/rtl-ais/rtl_ais.c:596: undefined reference to `rtlsdr_close'
/usr/bin/ld: rtl_ais.o: in function `rtl_ais_cleanup':
/home/pi/rtl-ais/rtl_ais.c:657: undefined reference to `rtlsdr_cancel_async'
/usr/bin/ld: /home/pi/rtl-ais/rtl_ais.c:668: undefined reference to `rtlsdr_cancel_                                         async'
/usr/bin/ld: /home/pi/rtl-ais/rtl_ais.c:673: undefined reference to `rtlsdr_close'
/usr/bin/ld: convenience.o: in function `nearest_gain':
/home/pi/rtl-ais/convenience.c:116: undefined reference to `rtlsdr_set_tuner_gain_m                                         ode'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:121: undefined reference to `rtlsdr_get                                         _tuner_gains'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:126: undefined reference to `rtlsdr_get                                         _tuner_gains'
/usr/bin/ld: convenience.o: in function `verbose_set_frequency':
/home/pi/rtl-ais/convenience.c:142: undefined reference to `rtlsdr_set_center_freq'
/usr/bin/ld: convenience.o: in function `verbose_set_sample_rate':
/home/pi/rtl-ais/convenience.c:154: undefined reference to `rtlsdr_set_sample_rate'
/usr/bin/ld: convenience.o: in function `verbose_direct_sampling':
/home/pi/rtl-ais/convenience.c:166: undefined reference to `rtlsdr_set_direct_sampl                                         ing'
/usr/bin/ld: convenience.o: in function `verbose_offset_tuning':
/home/pi/rtl-ais/convenience.c:183: undefined reference to `rtlsdr_set_offset_tunin                                         g'
/usr/bin/ld: convenience.o: in function `verbose_auto_gain':
/home/pi/rtl-ais/convenience.c:195: undefined reference to `rtlsdr_set_tuner_gain_m                                         ode'
/usr/bin/ld: convenience.o: in function `verbose_gain_set':
/home/pi/rtl-ais/convenience.c:207: undefined reference to `rtlsdr_set_tuner_gain_m                                         ode'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:212: undefined reference to `rtlsdr_set                                         _tuner_gain'
/usr/bin/ld: convenience.o: in function `verbose_ppm_set':
/home/pi/rtl-ais/convenience.c:226: undefined reference to `rtlsdr_set_freq_correct                                         ion'
/usr/bin/ld: convenience.o: in function `verbose_ppm_eeprom':
/home/pi/rtl-ais/convenience.c:241: undefined reference to `rtlsdr_get_usb_strings'
/usr/bin/ld: convenience.o: in function `verbose_reset_buffer':
/home/pi/rtl-ais/convenience.c:266: undefined reference to `rtlsdr_reset_buffer'
/usr/bin/ld: convenience.o: in function `verbose_device_search':
/home/pi/rtl-ais/convenience.c:277: undefined reference to `rtlsdr_get_device_count                                         '
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:284: undefined reference to `rtlsdr_get                                         _device_usb_strings'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:297: undefined reference to `rtlsdr_get                                         _device_usb_strings'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:301: undefined reference to `rtlsdr_get                                         _device_name'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:307: undefined reference to `rtlsdr_get                                         _device_usb_strings'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:317: undefined reference to `rtlsdr_get                                         _device_usb_strings'
/usr/bin/ld: /home/pi/rtl-ais/convenience.c:324: undefined reference to `rtlsdr_get                                         _device_name'
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: rtl_ais] Fehler 1

**Comment by dgiardini** [comment]
Try this:
Edit  Makefile line 3, change to:

LDFLAGS+=-lpthread -lm -lrtlsdr -L /usr/lib/arm-linux-gnueabihf/

Good luck, David

**Comment by whallmann** [comment]
Hi David
thanks for support. i already found the solution, everthing runs fine.
Another question. Both channels in Germany are used, but the ais dispatcher
counts only Status on Channel-B. Is this ok while no channel-id is
available?
cu
Wolf

dgiardini ***@***.***> schrieb am So., 22. Mai 2022, 21:57:
