### ISSUE TITLE
TCP server stops streaming; bug or intentional?

### ISSUE THREAD

**Issue by mik3y** [dgiardini/rtl-ais#33]
Hi there! I have what may be a silly question about the intended usage of the TCP listener (`./rtl_ais -T`)

When I run `rtl_ais` in this mode, and connect a new client to the host and port (eg `telnet localhost 10110`), the client receives a burst of buffered messages, then nothing further. Sending a character from the client causes the connection to be closed.

What I'd expect: The client receives buffered messages, _and continues to receive all newly-parsed messages_, until either side terminates the connection.

Taking a look at docs and code, I can't quite see anything I'm doing wrong, so I'm thinking this is either intentional or perhaps just disused. Before I prep a PR, can you share any insight? Thanks for maintaining this!

**Comment by dgiardini** [comment]
Hi Mike
  This way works fine together with OpenCPN that open a connection,
receive the messages and then close the connection.
  Would not be difficult to make it work the way you expect (that is
very reasonable way), but I don't know if would worth to do it.
Best regards, David

**Comment by mik3y** [comment]
Hey David - Thanks very much for the fast reply! That makes sense now; OpenCPN is the main client, and it sounds like it is perfectly functional repeatedly connecting.

I'm going to prepare a patch that can keep the connection open, and will send it your way. I'll do so in a way which avoids breaking existing applications like this; perhaps a command line flag for "keep TCP connection open".

FYI: This mode of operation would make rtl_ais work like similar applications that exist in the ADS-B (plane tracking) world: dump1090 and readsb/readsb-proto being the most popular. I am building a web application that can visualize data from both ([airdash](https://github.com/mik3y/airdash)), so it will be great to support ais similarly. Cheers!

**Comment by mik3y** [comment]
Just a short update: I've got this feature implemented now, in my branch here: https://github.com/mik3y/rtl-ais/commit/8507fbc6d45d36d6f2c2788352889d1d49ec4d3e . It is implemented as an opt-in feature (`-k`) so that if anything depends on the old behavior, it shouldn't break.

I'll be giving it some time testing, then will PR here. Cheers!
