### ISSUE TITLE
main.h file required 

### ISSUE THREAD

**Issue by saikumarelab** [dgiardini/rtl-ais#37]
Hi dgiardini, I'm looking for main.h file which is required to build the https://github.com/videgro/Ships since the main.h file is imported during the android build. So if possible, kindly help us with requirement.

Thanks in Advance,
SAI

**Comment by dgiardini** [comment]
Hi
  There is no "main.h" in the source tree of rtl-ais. Probably they used a
custom version of rtl-ais; I suggest you trying to contact Ships software
manteiners
Regards, David
