### ISSUE TITLE
Completely useless heap of shit

### ISSUE THREAD

**Issue by pb2888** [dgiardini/rtl-ais#42]
theres NO config file to change the IP and port due to the commands NOT workin no matter what is done
and theres no gui and NO way to get ais dispatcher to connect to it cause that fuckin shit comes up with "Error bind: Address already in use" when there is literally NOTHING ELSE runnin to use it

**Comment by dgiardini** [comment]
Thanks for your feedback, here there are some starting points for you:

https://www.wikihow.com/Use-a-Computer
https://www.londonschool.com/blog/5-tips-polite-and-diplomatic-language/
