### ISSUE TITLE
Missing 'rtl-sdr.h' 

### ISSUE THREAD

**Issue by mikekolling1966** [dgiardini/rtl-ais#44]
make
cc -c rtl_ais.c -o rtl_ais.o -O2 -g -Wall   -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener  -I/usr/local/include/ -I/tmp/libusb/include/libusb-1.0 -I/tmp/rtl-sdr/include
rtl_ais.c:42:10: fatal error: 'rtl-sdr.h' file not found
#include <rtl-sdr.h>

**Comment by dgiardini** [comment]
You need to install the rtl-sdr lib. You can try "sudo apt-get install
librtlsdr-dev", or google how  to install librtlsdr on your system.

**Comment by dgiardini** [comment]
'rtl-sdr.h' file not found

**Comment by mikekolling1966** [comment]
Hi

Its on a MAC, hence that command wont work.

I have installed librtlsdr already using brew (homebrew) but that does not have the DEV one on it.


***@***.*** rtl-ais % brew install librtlsdr-dev

==> Downloading https://formulae.brew.sh/api/formula.jws.json

######################################################################### 100.0%

==> Downloading https://formulae.brew.sh/api/cask.jws.json

######################################################################### 100.0%

Warning: No available formula with the name "librtlsdr-dev". Did you mean librtlsdr?

==> Searching for similarly named formulae and casks...

==> Formulae

librtlsdr ✔




So how do I install the DEV one.

Kind regards

Mike


MIKE KOLLING DIRECTOR, MANXMAN CONSULTING LTD.
07400 686186 (w)    |  ***@***.******@***.***>

***@***.***                                              ***@***.***
http://www.manxmanconsulting.com




From: dgiardini ***@***.***>
Reply to: dgiardini/rtl-ais ***@***.***>
Date: Monday, 20 November 2023 at 16:54
To: dgiardini/rtl-ais ***@***.***>
Cc: Mike Kolling ***@***.***>, Author ***@***.***>
Subject: Re: [dgiardini/rtl-ais] Missing 'rtl-sdr.h' (Issue #44)

You need to install the rtl-sdr lib. You can try "sudo apt-get install
librtlsdr-dev", or google how to install librtlsdr on your system.

**Comment by dgiardini** [comment]
You can build and install directly from source code. Show these
instructions:

https://gist.github.com/uname-yang/888674925fa8a3bed75a4fc5b9c952f7

When you install the libs, you are installing the missing file too. You'll
need not only rtl-sdr.h but other files in order to compile and run
rtl-ais. The instructions above should work for you.

Regards, David
