### ISSUE TITLE
upgraded RTLSDR from v3 to v4, the rtl_ais doesnt work

### ISSUE THREAD

**Issue by Mbungurz** [dgiardini/rtl-ais#48]
hello, im using rtlsdr v4 to runing your program, but not working like when i use rtlsdr v3
it just got stuck 

root@armbian:~/rtl-ais# rtl_ais -n -h 192.168.12.255 -P 11223
Edge tuning disabled.
DC filter enabled.
RTL AGC disabled.
Internal AIS decoder enabled.
Buffer size: 163.84 mS
Downsample factor: 64
Low pass: 25000 Hz
Output: 48000 Hz
Found 1 device(s):
  0:  RTLSDRBlog, Blog V4, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
Log NMEA sentences to console ON
Broadcast address detected. Setting SO_BROADCAST option to socket.
AIS data will be sent to 192.168.12.255 port 11223
Tuner gain set to automatic.
[R82XX] PLL not locked!
Tuned to 162000000 Hz.
[R82XX] PLL not locked!
Sampling at 1600000 S/s.
Allocating 12 zero-copy buffers

is there any update??

**Comment by dgiardini** [comment]
This is the first report about the issue.
Check if the program is really stucked, print the statistics more often
(i.e  -S 2).
Check if the rtl-sdr device is working properly, you can test it using the
rtl_fm program.
If you can,  give it a try in another system to be sure that is not a
hardware related issue.

Regards, David

**Comment by dgiardini** [comment]
No feedback, closing
